(()=>{
'use strict';
const app=document.getElementById('excel-app');
const STORE='vidlik-hotkeys-desktop-sectors-v1';
const params=new URLSearchParams(location.search);
let level=Math.max(1,Math.min(10,parseInt(params.get('level')||'1',10)||1));
const ROWS=14,COLS=8,letters='ABCDEFGH';
const baseRows=[
 ['Товар','К-сть','Ціна','Сума','Статус','Категорія','Дата','Відповідальний'],
 ['Кабель',12,350,'','Є','Зв’язок','01.09.2026','Іван'],
 ['Антена',4,8500,'','Є','РЕБ','01.09.2026','Олег'],
 ['Модуль',7,4200,'','Немає','РЕБ','02.09.2026','Анна'],
 ['Акумулятор',18,2100,'','Є','Живлення','02.09.2026','Іван'],
 ['Перехідник',25,180,'','Є','Зв’язок','03.09.2026','Марія'],
 ['Ноутбук',3,28500,'','Є','ІТ','03.09.2026','Олег'],
 ['Рація',9,6700,'','Немає','Зв’язок','04.09.2026','Анна']
];
const missions=[
 {title:'Навігація без миші',desc:'Переміщуй активну клітинку по робочій таблиці. Важливий результат, а не єдина “правильна” комбінація.',goals:[gPos('A2','Перейди до A2'),gPos('A8','Перейди до останнього запису в стовпці A'),gPos('H8','Перейди до H8')]},
 {title:'Виділення даних',desc:'Навчись виділяти робочі діапазони клавіатурою.',goals:[gRange('A2','H8','Виділи весь масив записів A2:H8'),gRange('B2','B8','Виділи кількість B2:B8'),gRange('A1','H1','Виділи рядок заголовків')]},
 {title:'Формула розрахунку',desc:'Створи формулу вартості та заповни нею стовпець.',goals:[gFormula('D2','=B2*C2','У D2 введи =B2*C2'),gFormula('D8','=B8*C8','Заповни формулу до D8')]},
 {title:'Форматування таблиці',desc:'Підготуй таблицю до читання: заголовки та числовий стовпець.',goals:[gBold('A1','H1','Зроби заголовки напівжирними'),gRange('D2','D8','Виділи стовпець сум D2:D8')]},
 {title:'Підсумки',desc:'Порахуй загальну суму даних формулою.',goals:[gFormula('D10','=SUM(D2:D8)','У D10 введи =SUM(D2:D8)'),gFormula('B10','=SUM(B2:B8)','У B10 порахуй загальну кількість')]},
 {title:'Логічні формули',desc:'Додай просту бізнес-логіку через IF.',goals:[gFormula('E2','=IF(D2>10000;"Висока";"Звичайна")','У E2 введи IF для оцінки суми'),gFormula('E8','=IF(D8>10000;"Висока";"Звичайна")','Заповни формулу до E8')]},
 {title:'Таблиця та фільтри',desc:'Перетвори діапазон на робочу таблицю і ввімкни фільтри.',goals:[gRange('A1','H8','Виділи A1:H8'),gFlag('table','Перетвори діапазон на таблицю · Ctrl+T'),gFlag('filter','Увімкни фільтри · Ctrl+Shift+L')]},
 {title:'Аркуші книги',desc:'Працюй із книгою без миші.',goals:[gSheet(1,'Перейди на аркуш “Звіт” · Ctrl+PageDown'),gSheet(0,'Повернись на “Дані” · Ctrl+PageUp')]},
 {title:'Пошук і виправлення',desc:'Знайди проблемну клітинку та виправ формулу.',setup:'error',goals:[gPos('D6','Знайди помилку в D6'),gFormula('D6','=B6*C6','Виправ формулу в D6 на =B6*C6')]},
 {title:'Контрольна робоча місія',desc:'Без покрокових підказок підготуй дані до передачі. Можна використовувати будь-який клавіатурний маршрут.',goals:[gFormula('D2','=B2*C2','Розрахуй суму в D2'),gFormula('D8','=B8*C8','Заповни суми до D8'),gFormula('D10','=SUM(D2:D8)','Порахуй підсумок у D10'),gRange('A1','H8','Виділи робочий масив'),gFlag('table','Створи таблицю'),gFlag('filter','Увімкни фільтри')]}
];
function gPos(a,text){return{type:'pos',a,text}}function gRange(a,b,text){return{type:'range',a,b,text}}function gFormula(a,v,text){return{type:'formula',a,v,text}}function gBold(a,b,text){return{type:'bold',a,b,text}}function gFlag(flag,text){return{type:'flag',flag,text}}function gSheet(n,text){return{type:'sheet',n,text}}
let state,editing=false,editBuffer='',goal=0,seconds=0,errors=0,actions=0,mouse=0,timer=null,toast='';
function cellKey(r,c){return letters[c]+(r+1)}function parseAddr(a){return{r:Math.max(0,parseInt(a.slice(1),10)-1),c:letters.indexOf(a[0].toUpperCase())}}
function reset(){state={active:{r:1,c:0},anchor:{r:1,c:0},cells:{},bold:new Set(),table:false,filter:false,sheet:0};for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)state.cells[cellKey(r,c)]=baseRows[r]?.[c]??'';if(missions[level-1].setup==='error')state.cells.D6='=B6+C6';goal=0;seconds=errors=actions=mouse=0;editing=false;editBuffer='';toast='';clearInterval(timer);timer=setInterval(()=>{seconds++;paintStats()},1000);render();checkGoal()}
function normFormula(v){return String(v||'').replace(/,/g,';').replace(/\s+/g,'').toUpperCase()}
function selectedBounds(){return{r1:Math.min(state.active.r,state.anchor.r),r2:Math.max(state.active.r,state.anchor.r),c1:Math.min(state.active.c,state.anchor.c),c2:Math.max(state.active.c,state.anchor.c)}}
function sameRange(a,b){const x=parseAddr(a),y=parseAddr(b),s=selectedBounds();return s.r1===Math.min(x.r,y.r)&&s.r2===Math.max(x.r,y.r)&&s.c1===Math.min(x.c,y.c)&&s.c2===Math.max(x.c,y.c)}
function goalDone(g){if(g.type==='pos'){const p=parseAddr(g.a);return state.active.r===p.r&&state.active.c===p.c}if(g.type==='range')return sameRange(g.a,g.b);if(g.type==='formula')return normFormula(state.cells[g.a])===normFormula(g.v);if(g.type==='bold'){const a=parseAddr(g.a),b=parseAddr(g.b);for(let r=a.r;r<=b.r;r++)for(let c=a.c;c<=b.c;c++)if(!state.bold.has(cellKey(r,c)))return false;return true}if(g.type==='flag')return!!state[g.flag];if(g.type==='sheet')return state.sheet===g.n;return false}
function checkGoal(){const m=missions[level-1];while(goal<m.goals.length&&goalDone(m.goals[goal])){goal++;toast='✓ Завдання виконано';render();if(goal>=m.goals.length){finish();return}}render()}
function finish(){clearInterval(timer);saveCompleted(level);setTimeout(()=>{const efficiency=Math.max(0,100-errors*8-mouse*6-Math.max(0,actions-28));const score=Math.max(0,1000-errors*30-mouse*15+efficiency*3-Math.max(0,seconds-90));app.innerHTML=`<section class="xl-complete"><div class="xl-card"><span class="xl-kicker">СЕКТОР 03 · РІВЕНЬ ${String(level).padStart(2,'0')}</span><h1>Місію завершено</h1><div class="xl-score">${Math.round(efficiency)}%</div><p>Ефективність клавіатури</p><p>XP: <b>${Math.round(score)}</b> · Час: ${fmt(seconds)} · Помилки: ${errors} · Миша: ${mouse}</p><div class="xl-actions"><button class="xl-primary" id="next">${level<10?'Наступний рівень →':'До сектора'}</button><button class="xl-secondary" id="again">↻ Повторити</button></div></div></section>`;document.getElementById('again').onclick=reset;document.getElementById('next').onclick=()=>{if(level<10){level++;history.replaceState(null,'',`excel-sector.html?level=${level}&from=briefing`);reset()}else location.href='module-briefing.html?sector=3'}},550)}
function saveCompleted(n){try{const p=JSON.parse(localStorage.getItem(STORE)||'{}')||{};p[3]=Array.isArray(p[3])?p[3]:[];if(!p[3].includes(n))p[3].push(n);p[3].sort((a,b)=>a-b);localStorage.setItem(STORE,JSON.stringify(p))}catch(e){}}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function displayValue(addr){const raw=state.cells[addr];if(typeof raw!=='string'||!raw.startsWith('='))return raw;try{return evalFormula(raw)}catch(e){return '#ПОМИЛКА!'}}
function num(a){const v=displayValue(a);return Number(v)||0}
function evalFormula(f){const u=f.toUpperCase();let m;if((m=u.match(/^=([A-H]\d+)\*([A-H]\d+)$/)))return num(m[1])*num(m[2]);if((m=u.match(/^=SUM\(([A-H]\d+):([A-H]\d+)\)$/))){const a=parseAddr(m[1]),b=parseAddr(m[2]);let s=0;for(let r=a.r;r<=b.r;r++)for(let c=a.c;c<=b.c;c++)s+=num(cellKey(r,c));return s}if((m=f.match(/^=IF\(([A-H]\d+)>(\d+);"([^"]+)";"([^"]+)"\)$/i)))return num(m[1])>Number(m[2])?m[3]:m[4];return '#ФОРМУЛА'}
function formulaBar(){const a=cellKey(state.active.r,state.active.c);return editing?editBuffer:state.cells[a]}
function render(){if(!state)return;const m=missions[level-1],s=selectedBounds();let cells='<div class="xl-cell head"></div>';for(let c=0;c<COLS;c++)cells+=`<div class="xl-cell head">${letters[c]}</div>`;for(let r=0;r<ROWS;r++){cells+=`<div class="xl-cell rowhead">${r+1}</div>`;for(let c=0;c<COLS;c++){const a=cellKey(r,c),active=r===state.active.r&&c===state.active.c,sel=r>=s.r1&&r<=s.r2&&c>=s.c1&&c<=s.c2;let cls=`xl-cell${active?' active':''}${sel?' selected':''}${state.bold.has(a)?' bold':''}${state.table&&r===0?' table-head':''}${state.filter&&r===0?' filtered':''}${missions[level-1].setup==='error'&&a==='D6'&&state.cells.D6==='=B6+C6'?' error':''}`;let v=displayValue(a);if(editing&&active)v=`<input id="xl-edit" class="xl-edit" value="${esc(editBuffer)}">`;cells+=`<div class="${cls}" data-r="${r}" data-c="${c}">${v}</div>`}}
app.innerHTML=`<header class="xl-top"><div class="xl-brand"><small>VIDLIK · КЛАВІАТУРНИЙ ПОЛІГОН</small><strong>Сектор 03 · Excel — робоча станція</strong></div><div class="xl-stat"><span>Час <b id="stat-time">${fmt(seconds)}</b></span><span>Дії <b>${actions}</b></span><span>Помилки <b>${errors}</b></span><span>Миша <b>${mouse}</b></span></div><button class="xl-btn" id="exit">ESC · ПАПКА СЕКТОРА</button></header><div class="xl-layout"><aside class="xl-mission"><span class="xl-kicker">РІВЕНЬ ${String(level).padStart(2,'0')} / 10</span><h1>${m.title}</h1><p>${m.desc}</p><div class="xl-objectives">${m.goals.map((g,i)=>`<div class="xl-objective ${i<goal?'is-done':i===goal?'is-current':''}"><i>${i<goal?'✓':i+1}</i><span>${g.text}</span></div>`).join('')}</div><div class="xl-help">Клавіатура: стрілки · Tab · Enter · Shift для виділення · Ctrl+стрілки до краю · Ctrl+Shift+стрілки для діапазону · F2 або “=” для редагування · Ctrl+D заповнити вниз · Ctrl+B формат · Ctrl+T таблиця.</div></aside><section class="xl-workstation"><div class="xl-titlebar"><span>Книга VIDLIK.xlsx</span><span>— □ ×</span></div><div class="xl-ribbon"><span class="xl-tab active">Основне</span><span class="xl-tab">Вставлення</span><span class="xl-tab">Формули</span><span class="xl-tab">Дані</span></div><div class="xl-formula"><div class="xl-namebox">${cellKey(state.active.r,state.active.c)}</div><div class="xl-fx">fx</div><div class="xl-formula-value">${esc(formulaBar())}</div></div><div class="xl-grid-wrap"><div class="xl-grid">${cells}</div>${toast?`<div class="xl-toast">${toast}</div>`:''}</div><div class="xl-sheetbar"><span class="xl-sheet ${state.sheet===0?'active':''}">Дані</span><span class="xl-sheet ${state.sheet===1?'active':''}">Звіт</span></div></section></div>`;
document.getElementById('exit').onclick=()=>location.href='module-briefing.html?sector=3';document.querySelectorAll('.xl-cell[data-r]').forEach(el=>el.onclick=()=>{mouse++;state.active={r:+el.dataset.r,c:+el.dataset.c};state.anchor={...state.active};render();checkGoal()});if(editing){const input=document.getElementById('xl-edit');if(input){input.focus();input.setSelectionRange(input.value.length,input.value.length);input.oninput=e=>{editBuffer=e.target.value}}}}
function paintStats(){const e=document.getElementById('stat-time');if(e)e.textContent=fmt(seconds)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function move(dr,dc,extend=false,jump=false){let r=state.active.r,c=state.active.c;if(jump){if(dr<0)r=0;if(dr>0)r=Math.min(ROWS-1,7);if(dc<0)c=0;if(dc>0)c=COLS-1}else{r=Math.max(0,Math.min(ROWS-1,r+dr));c=Math.max(0,Math.min(COLS-1,c+dc))}state.active={r,c};if(!extend)state.anchor={r,c}}
function startEdit(seed=''){editing=true;const a=cellKey(state.active.r,state.active.c);editBuffer=seed||String(state.cells[a]??'');render()}
function commitEdit(){const a=cellKey(state.active.r,state.active.c);state.cells[a]=editBuffer;editing=false;actions++;move(1,0,false,false);checkGoal()}
window.addEventListener('keydown',e=>{if(!state)return;if(e.key==='Escape'){e.preventDefault();if(editing){editing=false;render();return}location.href='module-briefing.html?sector=3';return}if(editing){if(e.key==='Enter'){e.preventDefault();commitEdit()}else if(e.key==='Escape'){editing=false;render()}return}let handled=true;const shift=e.shiftKey,ctrl=e.ctrlKey;if(e.key==='ArrowUp')move(-1,0,shift,ctrl);else if(e.key==='ArrowDown')move(1,0,shift,ctrl);else if(e.key==='ArrowLeft')move(0,-1,shift,ctrl);else if(e.key==='ArrowRight')move(0,1,shift,ctrl);else if(e.key==='Tab')move(0,shift?-1:1,false,false);else if(e.key==='Enter')move(1,0,false,false);else if(e.key==='F2')startEdit();else if(e.key==='='&&!ctrl&&!e.altKey)startEdit('=');else if(ctrl&&e.key.toLowerCase()==='b'){const s=selectedBounds();for(let r=s.r1;r<=s.r2;r++)for(let c=s.c1;c<=s.c2;c++)state.bold.add(cellKey(r,c));actions++}else if(ctrl&&e.key.toLowerCase()==='t'){state.table=true;actions++}else if(ctrl&&shift&&e.key.toLowerCase()==='l'){state.filter=!state.filter;actions++}else if(ctrl&&e.key==='PageDown'){state.sheet=1;actions++}else if(ctrl&&e.key==='PageUp'){state.sheet=0;actions++}else if(ctrl&&e.key.toLowerCase()==='d'){const s=selectedBounds(),src=state.cells[cellKey(s.r1,s.c1)];for(let r=s.r1;r<=s.r2;r++){const dest=cellKey(r,s.c1);state.cells[dest]=typeof src==='string'&&src.startsWith('=')?shiftFormula(src,r-s.r1,0):src}actions++}else if(ctrl&&e.key===' '){state.anchor={r:0,c:state.active.c};state.active={r:ROWS-1,c:state.active.c};actions++}else if(shift&&e.key===' '){state.anchor={r:state.active.r,c:0};state.active={r:state.active.r,c:COLS-1};actions++}else if(e.key.length===1&&!ctrl&&!e.altKey){startEdit(e.key)}else handled=false;if(handled){e.preventDefault();actions++;toast='';render();checkGoal()}},true);
function shiftFormula(f,dr,dc){return f.replace(/([A-H])(\d+)/g,(_,l,n)=>letters[Math.max(0,Math.min(COLS-1,letters.indexOf(l)+dc))]+Math.max(1,parseInt(n,10)+dr))}
reset();
})();
