(()=>{
'use strict';
const mon=document.querySelector('.monitor-screen'),desk=document.getElementById('desktopIcons'),bar=mon?.querySelector('.taskbar');if(!mon||!desk||!bar)return;
let uid=0,enabled=false,lang='UKR',mode='desktop',path=[],sel=new Set(),clip=null,trash=[],history=[],future=[],editor=null,activeCell='A1',excelFile=null;
const folder=(name,children=[])=>({id:'d'+(++uid),type:'folder',name,children}),file=(name,kind='file',x={})=>({id:'f'+(++uid),type:'file',kind,name,...x});
const root=folder('Цей ПК',[folder('Документи',[folder('Навчання',[file('пам’ятка_VIDLIK.txt','txt')]),folder('Звіти',[file('звіт_серпень.xlsx','xlsx'),file('табель.xlsx','xlsx')]),folder('Архів',[file('267.xlsx','xlsx',{locked:true}),file('журнал_переміщень.xlsx','xlsx',{journal:true})]),folder('temp',[file('чернетка.txt','txt')]),file('report_old.xlsx','xlsx')]),folder('Системні файли',[file('VIDLIK_OS.cfg','txt',{system:true}),file('session.log','txt',{system:true})])]);
const cells={B2:'12',B3:'18',B4:'7',B5:'23',B6:'15',B7:'9',B8:'16'};
const layer=document.createElement('div');layer.className='os-layer os-ui';mon.insertBefore(layer,bar);
const ctx=document.createElement('div');ctx.className='os-context-menu os-ui';ctx.hidden=true;mon.append(ctx);
const toast=document.createElement('div');toast.className='os-toast os-ui';mon.append(toast);
const start=document.createElement('div');start.className='os-start-menu os-ui';start.hidden=true;start.innerHTML='<div class="os-start-title">VIDLIK OS</div><button data-app="pc">▣ <span>Цей ПК</span></button><button data-app="docs">📁 <span>Документи</span></button><button data-app="excel">▦ <span>Microsoft Excel</span></button><button data-app="trash">⌫ <span>Кошик</span></button>';mon.append(start);
function taskbar(){const s=bar.querySelector('.start-mark');if(s){const b=document.createElement('button');b.id='osStartButton';b.className='start-mark os-taskbar-button os-ui';b.textContent='⊞';s.replaceWith(b)}const old=[...bar.children].find(x=>x.textContent.trim()==='UKR');if(old){const w=document.createElement('span');w.className='os-language-wrap os-ui';w.innerHTML='<button id="osLanguageButton" class="os-language-button">UKR</button><span id="osLanguageMenu" class="os-language-menu" hidden><button data-lang="UKR"><b>●</b> Українська <small>UKR</small></button><button data-lang="ENG"><b>○</b> English <small>ENG</small></button></span>';old.replaceWith(w)}const sp=bar.querySelector('.taskbar-spacer');if(sp){const r=document.createElement('span');r.id='osRunningApps';r.className='os-running-apps';bar.insertBefore(r,sp)}}taskbar();
const langBtn=document.getElementById('osLanguageButton'),langMenu=document.getElementById('osLanguageMenu'),startBtn=document.getElementById('osStartButton'),running=document.getElementById('osRunningApps');
const clone=v=>JSON.parse(JSON.stringify(v)),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function note(t){toast.textContent=t;toast.classList.remove('show');void toast.offsetWidth;toast.classList.add('show');clearTimeout(note.t);note.t=setTimeout(()=>toast.classList.remove('show'),1450)}
function closeMenus(){ctx.hidden=true;start.hidden=true;if(langMenu)langMenu.hidden=true}
function snap(){return JSON.stringify({children:root.children,trash,uid})}function checkpoint(){history.push(snap());if(history.length>25)history.shift();future=[]}function restore(s){const x=JSON.parse(s);root.children=x.children;trash=x.trash;uid=x.uid;sel.clear();render()}function undo(){if(!history.length)return note('Немає дій для скасування');future.push(snap());restore(history.pop());note('Дію скасовано')}function redo(){if(!future.length)return note('Немає дій для повторення');history.push(snap());restore(future.pop());note('Дію повторено')}
function at(p=path){let d=root;for(const id of p){d=d.children.find(x=>x.id===id&&x.type==='folder')||root}return d}function names(){let d=root,a=['Цей ПК'];for(const id of path){d=d.children.find(x=>x.id===id&&x.type==='folder');if(!d)break;a.push(d.name)}return a}function find(id,n=root){for(const x of n.children||[]){if(x.id===id)return{parent:n,item:x};if(x.type==='folder'){const q=find(id,x);if(q)return q}}return null}
function items(){return mode==='trash'?trash:at().children}function item(){const id=[...sel][0];return items().find(x=>x.id===id)||null}function icon(x){return x.type==='folder'?'📁':x.kind==='xlsx'?'▦':x.kind==='txt'?'▤':'◇'}function type(x){return x.type==='folder'?'Папка':x.kind==='xlsx'?'Аркуш Microsoft Excel':x.kind==='txt'?'Текстовий документ':'Файл'}
function unique(d,n){if(!d.children.some(x=>x.name.toLowerCase()===n.toLowerCase()))return n;const k=n.lastIndexOf('.'),b=k>0?n.slice(0,k):n,e=k>0?n.slice(k):'';let i=2;while(d.children.some(x=>x.name.toLowerCase()===`${b} (${i})${e}`.toLowerCase()))i++;return`${b} (${i})${e}`}
function desktop(){layer.replaceChildren();mode='desktop';path=[];sel.clear();editor=null;if(running)running.replaceChildren();mon.classList.add('os-ready')}
function win(title,app){layer.innerHTML=`<section class="os-window"><header class="os-window-titlebar"><strong>${esc(title)}</strong><span class="os-window-actions"><button data-win="min">—</button><button data-win="close">×</button></span></header><div class="os-window-body"></div></section>`;if(running)running.innerHTML=`<button class="os-running-button">${esc(title)}</button>`;return layer.querySelector('.os-window-body')}
function explorer(){const title=mode==='trash'?'Кошик':names().at(-1),b=win(title,'explorer');b.innerHTML=`<div class="os-explorer-toolbar"><button data-act="back" ${mode==='trash'||!path.length?'disabled':''}>←</button><button data-act="new" ${mode==='trash'?'disabled':''}>＋</button><div class="os-address">${mode==='trash'?'Кошик':esc(names().join(' › '))}</div><button data-act="search">⌕</button></div><div class="os-search-row"><span>⌕</span><input id="osSearch" readonly placeholder="Пошук"><button data-act="clear">×</button></div><div class="os-explorer-main"><nav class="os-sidebar"><button data-nav="pc">▣ Цей ПК</button><button data-nav="docs">📁 Документи</button><button data-nav="reports">📁 Звіти</button><button data-nav="archive">📁 Архів</button><button data-nav="trash">⌫ Кошик</button></nav><div class="os-file-pane"><div class="os-file-head"><span>Ім’я</span><span>Тип</span><span>Розмір</span></div><div class="os-file-list"></div></div></div><footer class="os-statusbar"><span id="osCount"></span><span id="osSel"></span></footer>`;files()}
function files(filter=''){const list=layer.querySelector('.os-file-list');if(!list)return;const a=items().filter(x=>x.name.toLowerCase().includes(filter.toLowerCase()));list.innerHTML=a.map(x=>`<button class="os-file-item ${sel.has(x.id)?'selected':''}" data-id="${x.id}"><span class="os-file-name"><i>${icon(x)}</i><b>${esc(x.name)}</b></span><span>${type(x)}</span><span>—</span></button>`).join('')||'<div class="os-empty">Папка порожня</div>';layer.querySelector('#osCount').textContent=`Об’єктів: ${a.length}`;layer.querySelector('#osSel').textContent=sel.size?`Вибрано: ${sel.size}`:''}
function nav(k){sel.clear();mode='explorer';const d=root.children.find(x=>x.name==='Документи');if(k==='pc')path=[];if(k==='docs')path=d?[d.id]:[];if(k==='reports'){const q=d?.children.find(x=>x.name==='Звіти');path=d&&q?[d.id,q.id]:[]}if(k==='archive'){const q=d?.children.find(x=>x.name==='Архів');path=d&&q?[d.id,q.id]:[]}if(k==='trash'){mode='trash';path=[]}explorer()}
function open(x){if(!x)return;if(mode==='trash')return note('Спочатку відновіть об’єкт');if(x.type==='folder'){path.push(x.id);sel.clear();explorer();return}if(x.locked)return dialog('Запис 267','Пряме відкриття заблоковано. Спочатку перевірте журнал переміщень.');if(x.kind==='xlsx')return excel(x);dialog(x.name,x.system?'Системний файл VIDLIK OS. Редагування обмежено.':'Документ відкрито у режимі перегляду.')}
function openApp(a){closeMenus();if(a==='pc')nav('pc');else if(a==='docs')nav('docs');else if(a==='trash')nav('trash');else if(a==='excel')excel(null)}
function remove(){if(!sel.size)return;if(mode==='trash'){checkpoint();trash=trash.filter(x=>!sel.has(x.id));sel.clear();explorer();return note('Видалено назавжди')}checkpoint();for(const id of [...sel]){const q=find(id);if(!q)continue;q.parent.children=q.parent.children.filter(x=>x.id!==id);trash.push({...clone(q.item),origin:path.slice()})}sel.clear();explorer();note('Переміщено до Кошика')}
function restoreTrash(){if(mode!=='trash'||!sel.size)return;checkpoint();for(const x of trash.filter(x=>sel.has(x.id))){const d=at(x.origin||[]),y=clone(x);delete y.origin;y.name=unique(d,y.name);d.children.push(y)}trash=trash.filter(x=>!sel.has(x.id));sel.clear();explorer();note('Відновлено')}
function copy(cut=false){if(!sel.size||mode==='trash')return;clip={cut,ids:[...sel],items:clone(items().filter(x=>sel.has(x.id)))};note(cut?'Вирізано у буфер VIDLIK':'Скопійовано у буфер VIDLIK')}
function reseed(x){x.id=(x.type==='folder'?'d':'f')+(++uid);(x.children||[]).forEach(reseed)}function paste(){if(!clip||mode==='trash')return;checkpoint();const d=at();if(clip.cut){for(const id of clip.ids){const q=find(id);if(!q)continue;q.parent.children=q.parent.children.filter(x=>x.id!==id);q.item.name=unique(d,q.item.name);d.children.push(q.item)}clip=null}else for(const o of clip.items){const x=clone(o);reseed(x);x.name=unique(d,x.name);d.children.push(x)}sel.clear();explorer();note('Вставлено')}
function newFolder(){if(mode==='trash')return;checkpoint();const d=at(),x=folder(unique(d,'Нова папка'));d.children.push(x);sel=new Set([x.id]);explorer();rename(x)}
function rename(x=item()){if(!x||mode==='trash'||x.system)return;const r=layer.querySelector(`[data-id="${x.id}"]`),b=r?.querySelector('.os-file-name b');if(!b)return;const input=document.createElement('input');input.className='os-inline-input';input.readOnly=true;input.value=x.name;b.replaceWith(input);input.focus();input.select();edit(input,v=>{v=v.trim();if(v&&v!==x.name){const d=find(x.id)?.parent;if(d.children.some(y=>y.id!==x.id&&y.name.toLowerCase()===v.toLowerCase()))return note('Таке ім’я вже існує');checkpoint();x.name=v;note('Перейменовано')}explorer()},()=>explorer())}
function properties(x=item()){if(!x)return;dialog('Властивості',`<b>${esc(x.name)}</b><br>Тип: ${type(x)}<br>Розташування: ${esc(names().join(' › '))}`,true)}
function dialog(t,m,html=false){const d=document.createElement('div');d.className='os-dialog-wrap os-ui';d.innerHTML=`<div class="os-dialog"><header>${esc(t)}</header><div class="os-dialog-copy">${html?m:esc(m)}</div><footer><button data-dlg>OK</button></footer></div>`;mon.append(d);d.querySelector('button').focus()}
function menu(e,x=null){e.preventDefault();const a=x?(mode==='trash'?[['restore','Відновити'],['delete','Видалити назавжди'],['prop','Властивості']]:[['open','Відкрити'],['rename','Перейменувати'],['copy','Копіювати'],['cut','Вирізати'],['delete','Видалити'],['prop','Властивості']]):[['new','Нова папка'],['paste','Вставити']];ctx.innerHTML=a.map(q=>`<button data-menu="${q[0]}" ${q[0]==='paste'&&!clip?'disabled':''}>${q[1]}</button>`).join('');ctx.dataset.id=x?.id||'';ctx.hidden=false;const r=mon.getBoundingClientRect();ctx.style.left=Math.max(4,Math.min(r.width-154,e.clientX-r.left))+'px';ctx.style.top=Math.max(4,Math.min(r.height-a.length*28-38,e.clientY-r.top))+'px'}
function excel(f){excelFile=f;mode='excel';const b=win(f?.name||'Microsoft Excel','excel');b.innerHTML=`<div class="os-excel-ribbon"><b>Файл</b><span>Основне</span><span>Вставлення</span><span>Формули</span><span class="os-excel-lang-note">Мова вводу: <strong id="osExcelLang">${lang}</strong></span></div><div class="os-formula-row"><span id="osCellName">${activeCell}</span><span>fx</span><input id="osFormula" readonly placeholder="Введіть значення або формулу"></div><div class="os-excel-grid" id="osGrid"></div><footer class="os-excel-status"><span>${esc(f?.name||'Книга1')}</span><span>Для формул перемкніть ENG мишкою.</span></footer>`;grid();layer.querySelector('#osFormula').addEventListener('click',()=>formula())}
function grid(){const g=layer.querySelector('#osGrid');if(!g)return;const cols=['','A','B','C','D','E','F'];let h='';for(let r=0;r<=9;r++)for(let c=0;c<7;c++){if(!r){h+=`<div class="os-xcell head">${cols[c]}</div>`;continue}if(!c){h+=`<div class="os-xcell head">${r}</div>`;continue}const a=cols[c]+r,j=excelFile?.journal?{A1:'Дата',B1:'Запис',C1:'Операція',A2:'05.09',B2:'251',C2:'архівовано',A3:'06.09',B3:'267',C3:'переміщено'}:{};h+=`<button class="os-xcell ${a===activeCell?'active':''}" data-cell="${a}">${esc(j[a]??cells[a]??'')}</button>`}g.innerHTML=h}
function formula(){const i=layer.querySelector('#osFormula');if(!i)return;i.value=cells[activeCell]||'';i.focus();i.setSelectionRange(i.value.length,i.value.length);edit(i,v=>{cells[activeCell]=v;grid();note(v.startsWith('=')?'Формулу введено':'Значення введено')},()=>{})}
const EN={};'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').forEach(c=>EN['Key'+c]=c.toLowerCase());const UA={KeyQ:'й',KeyW:'ц',KeyE:'у',KeyR:'к',KeyT:'е',KeyY:'н',KeyU:'г',KeyI:'ш',KeyO:'щ',KeyP:'з',BracketLeft:'х',BracketRight:'ї',KeyA:'ф',KeyS:'і',KeyD:'в',KeyF:'а',KeyG:'п',KeyH:'р',KeyJ:'о',KeyK:'л',KeyL:'д',Semicolon:'ж',Quote:'є',KeyZ:'я',KeyX:'ч',KeyC:'с',KeyV:'м',KeyB:'и',KeyN:'т',KeyM:'ь',Comma:'б',Period:'ю',Backquote:'ґ'};
const DS={Digit1:'!',Digit2:'@',Digit3:'#',Digit4:'$',Digit5:'%',Digit6:'^',Digit7:'&',Digit8:'*',Digit9:'(',Digit0:')'};function chr(e){if(e.code==='Space')return' ';if(/^Digit\d$/.test(e.code))return e.shiftKey?DS[e.code]:e.code.slice(-1);const m=lang==='ENG'?EN:UA;let c=m[e.code];if(c)return e.shiftKey?c.toUpperCase():c;if(lang==='ENG'){const p={Minus:['-','_'],Equal:['=','+'],Semicolon:[';',':'],Quote:["'",'"'],Comma:[',','<'],Period:['.','>'],Slash:['/','?'],BracketLeft:['[','{'],BracketRight:[']','}']};return p[e.code]?.[e.shiftKey?1:0]||''}return{Minus:'-',Equal:'=',Slash:'.'}[e.code]||''}
function edit(input,ok,cancel){editor={input,ok,cancel};input.classList.add('editing')}function end(ok=true){if(!editor)return;const e=editor;editor=null;e.input.classList.remove('editing');(ok?e.ok:e.cancel)?.(e.input.value)}function editKey(e){if(!editor)return false;const i=editor.input,k=e.key.toLowerCase();if(e.ctrlKey&&k==='a'){e.preventDefault();i.select();return true}if(e.key==='Enter'){e.preventDefault();end(true);return true}if(e.key==='Escape'){e.preventDefault();end(false);return true}if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();let a=i.selectionStart??i.value.length,b=i.selectionEnd??a;if(a===b){if(e.key==='Backspace'&&a)a--;else if(e.key==='Delete'&&b<i.value.length)b++}i.value=i.value.slice(0,a)+i.value.slice(b);i.setSelectionRange(a,a);return true}if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();let p=i.selectionStart??0;p=e.key==='Home'?0:e.key==='End'?i.value.length:e.key==='ArrowLeft'?Math.max(0,p-1):Math.min(i.value.length,p+1);i.setSelectionRange(p,p);return true}if(e.ctrlKey||e.altKey||e.metaKey)return false;const c=chr(e);if(!c)return false;e.preventDefault();const a=i.selectionStart??i.value.length,b=i.selectionEnd??a;i.value=i.value.slice(0,a)+c+i.value.slice(b);i.setSelectionRange(a+c.length,a+c.length);return true}
function edit(input,ok,cancel){editor={input,ok,cancel};input.classList.add('editing')}
function setLang(x){lang=x==='ENG'?'ENG':'UKR';langBtn.textContent=lang;langMenu.querySelectorAll('[data-lang]').forEach(b=>b.querySelector('b').textContent=b.dataset.lang===lang?'●':'○');closeMenus();layer.querySelector('#osExcelLang')&&(layer.querySelector('#osExcelLang').textContent=lang);note('МОВА ВВЕДЕННЯ · '+lang)}
function render(){mode==='desktop'?desktop():mode==='excel'?excel(excelFile):explorer()}
function key(e){if(!enabled||document.querySelector('.pause.visible'))return;if(editor&&editKey(e))return;const dlg=mon.querySelector('.os-dialog-wrap');if(dlg){if(e.key==='Escape'||e.key==='Enter'){e.preventDefault();dlg.remove()}return}const k=e.key.toLowerCase();if(e.ctrlKey&&!e.altKey&&!e.metaKey&&['a','c','x','v','z','y','f'].includes(k)){e.preventDefault();if(k==='a'&&(mode==='explorer'||mode==='trash')){sel=new Set(items().map(x=>x.id));files()}if(k==='c')copy(false);if(k==='x')copy(true);if(k==='v')paste();if(k==='z')undo();if(k==='y')redo();if(k==='f'&&(mode==='explorer'||mode==='trash')){const r=layer.querySelector('.os-search-row'),i=layer.querySelector('#osSearch');r.classList.add('visible');i.focus();edit(i,v=>files(v),()=>files())}return}if(mode==='explorer'||mode==='trash'){const a=items(),i=a.findIndex(x=>sel.has(x.id));if(['ArrowDown','ArrowUp','Home','End','PageDown','PageUp'].includes(e.key)){e.preventDefault();let n=i<0?0:i;n=e.key==='Home'?0:e.key==='End'?a.length-1:e.key==='ArrowDown'?n+1:e.key==='ArrowUp'?n-1:e.key==='PageDown'?n+5:n-5;n=Math.max(0,Math.min(a.length-1,n));sel.clear();a[n]&&sel.add(a[n].id);files();return}if(e.key==='Enter'){e.preventDefault();open(item());return}if(e.key==='F2'){e.preventDefault();rename();return}if(e.key==='Delete'){e.preventDefault();remove();return}if(e.key==='Backspace'&&mode!=='trash'&&path.length){e.preventDefault();path.pop();sel.clear();explorer();return}}if(mode==='excel'&&e.key==='Enter'){e.preventDefault();formula();return}if(e.key==='Escape'){e.preventDefault();if(!ctx.hidden||!start.hidden||!langMenu.hidden)return closeMenus();if(mode!=='desktop')return desktop();window.dispatchEvent(new CustomEvent('vidlik:pause-request'))}}
function enable(){if(enabled)return;enabled=true;mon.classList.add('os-enabled');desktop();const h=document.getElementById('help');if(h)h.innerHTML='<span><kbd>ENTER</kbd> відкрити</span><span><kbd>F2</kbd> перейменувати</span><span><kbd>DEL</kbd> видалити</span><span><kbd>CTRL+C/V</kbd> копія / вставка</span><span><kbd>ESC</kbd> назад / пауза</span>';const p=document.querySelector('#pause p');if(p)p.textContent='Enter / Space — продовжити';note('VIDLIK OS · РОБОЧА СТАНЦІЯ ГОТОВА')}
desk.addEventListener('click',e=>{if(!enabled)return;const b=e.target.closest('.desktop-icon');if(!b)return;desk.querySelectorAll('.desktop-icon').forEach(x=>x.classList.toggle('is-selected',x===b));if(e.detail===2)openApp(b.dataset.app==='folder'?'docs':b.dataset.app)});desk.addEventListener('contextmenu',e=>{if(!enabled)return;const b=e.target.closest('.desktop-icon');if(b){e.preventDefault();openApp(b.dataset.app==='folder'?'docs':b.dataset.app)}});
mon.addEventListener('click',e=>{if(!enabled)return;const w=e.target.closest('[data-win]');if(w)return desktop();const a=e.target.closest('[data-act]');if(a){if(a.dataset.act==='back'&&path.length){path.pop();sel.clear();explorer()}if(a.dataset.act==='new')newFolder();if(a.dataset.act==='search'){const r=layer.querySelector('.os-search-row'),i=layer.querySelector('#osSearch');r.classList.add('visible');i.focus();edit(i,v=>files(v),()=>files())}if(a.dataset.act==='clear')files();return}const n=e.target.closest('[data-nav]');if(n)return nav(n.dataset.nav);const f=e.target.closest('.os-file-item');if(f){if(e.ctrlKey)sel.has(f.dataset.id)?sel.delete(f.dataset.id):sel.add(f.dataset.id);else{sel.clear();sel.add(f.dataset.id)}files();if(e.detail===2)open(item());return}const c=e.target.closest('[data-cell]');if(c){activeCell=c.dataset.cell;layer.querySelector('#osCellName').textContent=activeCell;grid();return}const ap=e.target.closest('[data-app]');if(ap)return openApp(ap.dataset.app);const l=e.target.closest('[data-lang]');if(l)return setLang(l.dataset.lang);const d=e.target.closest('[data-dlg]');if(d)return d.closest('.os-dialog-wrap')?.remove()});
mon.addEventListener('contextmenu',e=>{if(!enabled)return;const f=e.target.closest('.os-file-item'),pane=e.target.closest('.os-file-pane');if(f||pane){if(f){sel.clear();sel.add(f.dataset.id);files()}menu(e,f?item():null)}});ctx.addEventListener('click',e=>{const b=e.target.closest('[data-menu]');if(!b||b.disabled)return;const a=b.dataset.menu;closeMenus();if(a==='open')open(item());if(a==='rename')rename();if(a==='copy')copy(false);if(a==='cut')copy(true);if(a==='delete')remove();if(a==='prop')properties();if(a==='restore')restoreTrash();if(a==='new')newFolder();if(a==='paste')paste()});
startBtn?.addEventListener('click',e=>{if(!enabled)return;e.stopPropagation();const x=start.hidden;closeMenus();start.hidden=!x});langBtn?.addEventListener('click',e=>{if(!enabled)return;e.stopPropagation();const x=langMenu.hidden;closeMenus();langMenu.hidden=!x});document.addEventListener('pointerdown',e=>{if(!mon.contains(e.target))closeMenus()});document.addEventListener('keydown',key,{capture:true});
window.addEventListener('vidlik:os-ready',enable);window.addEventListener('vidlik:os-reset',()=>{enabled=false;closeMenus();desktop();mon.classList.remove('os-enabled')});window.VIDLIK_OS={enable,setLanguage:setLang,get language(){return lang},openDesktopApp:openApp,getState:()=>({enabled,lang,mode,path:[...path],trash:clone(trash)})};
})();
